### ISSUE TITLE
Decide between LDP-BC and LDP-DC

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/tufts-implementation#22]
Run different versions and see if the DC part provides any benefits

**Comment by fbaumgardt** [comment]
Need to get ldp:membershipResource to work properly in Marmotta.

**Comment by balmas** [comment]
I think when I last checked, that wasn't fully implemented anywhere...

**Comment by fbaumgardt** [comment]
DCs are actually implemented in a number of stores and Marmotta should support it as well. Indirect Container are a different story, I think currently only Fedora has them. But we can definitely do without, I'm just trying to figure out if we can do with BCs only or if we need DVD to enable e.g. full URI support for container names.

**Comment by balmas** [comment]
yes that's right, it was the indirect container that wasn't implemented. ok, I'll stay quiet :-)

**Comment by fbaumgardt** [comment]
Noooooo!! Input is always welcome, especially when we have a chance to discuss this in next week's meeting.

**Comment by fbaumgardt** [comment]
Looking at Marmotta, Virtuoso and CarbonLDP, none of these implement DCs to a satisfying degree.

Currently I am looking at two major issues to resolve for a BC implementation of the Collections API:

* **retrieving collection metadata w/o collection items**
 a regular query on a container returns a list of *all* contained resources, i.e. metadata need to be anchored as resources inside a container so they can be queried individually
* **allow for resource URIs with arbitrary domains**
 using URL encoded URIs is possible but has issues, e.g. the slugs get encoded differently

**Comment by fbaumgardt** [comment]
Sub-issues are solved.
