### ISSUE TITLE
Decide on data structure for recursive MemberResultSets

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/tufts-implementation#27]
Flattened or nested ResultSets.

**Comment by fbaumgardt** [comment]
Currently doing flattened, because server-side it's quick and easy to revert to nested sets. However, returning nested sets would leave the decision to the client.

**Comment by fbaumgardt** [comment]
Things get a little ill defined when applying filters on recursive lists. E.g. if i'm filtering recursive collection C with dateAdded T, a sub-collection S has been added to C at T but its members M have been added to S at a different time -- what would be a sensible result?

**Comment by balmas** [comment]
that's a very interesting question! I wish I had a good answer...

**Comment by fbaumgardt** [comment]
It really is just a decision of filtering before or after the recursion, so it could be configurable e.g. with a url query parameter filtering=shallow or filtering=deep. I'd ask people and see if we can agree on a default behavior or parameterize it.

**Comment by fbaumgardt** [comment]
Duh, this should probably be nested sets given that we have /ops/flatten as a separate path. We should think about adding the member filters to /ops/<command> paths.

**Comment by fbaumgardt** [comment]
PS: I'm not a big fan of the design here -- we have /members to retrieve MemberResultSets, but then /ops/<command> also yield MemberResultSet.
