### ISSUE TITLE
Decide on source or scheme for ID minting

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/tufts-implementation#36]
Currently I'm adding a random string to a static base depending on the type, e.g. `urn:cite:test_collections.vXElYMekWECzBCEKvEdqsV`. Options are to either a) call a microservice that handles schemes and collision prevention, or to b) do it locally, keep the schemes ion configuration and check the DB for collisions. Naturally a) with fallback to b) would be best.

**Comment by balmas** [comment]
yes, I agree. even better might be to avoid urns altogether and use handles but we're not there yet.

**Comment by fbaumgardt** [comment]
Fixed in https://github.com/RDACollectionsWG/tufts-implementation/commit/79623b0c0f0ccb05c658bd74b7ecf6081cad299e
